### ISSUE TITLE
Kod

### ISSUE THREAD

**Issue by SheriefBadran** [ba222ec/1DV450_ba222ec#10]
Jag tycker koden är lätt att läsa och förstå. Jag är själv helt ny med rails och är osäker på vilka olika tillvägagångssätt som är bra och mindre bra. Det känns som att du kanske borde lägga lite mer tid i filen routes för att sätta mer logiska routes i applikationen. När en användare listar sina applikationer så kanske det ska vara på /applications genom att lägga till resources :sessions och /applications på sessions#index alternativt visa /user/id som du gör när man exempelvis tagit bort en applikation.

Ytterligare ett tips är att lägga till validates :password, length: {minimum: 8}  i din Users modell som åtgärd till att man nu kan registrera sig med lösenord som bara har ett fåtal tecken.

Dock kollar du att api nyckeln är unik, det glömde jag!! :(

**Comment by SvanteArvedson** [comment]
Validering av lösenordens längd är åtgärdat med commit d8e53489e45eb7b0c884f0c8b36172b1638f8a7f
