### ISSUE TITLE
Övrigt

### ISSUE THREAD

**Issue by SheriefBadran** [ba222ec/1DV450_ba222ec#11]
Du gjorde samma misstag som jag själv gjort i filen seed. Glöm inte att köra metoden save på alla objekt du skapat. Du kunde även haft en tydligare installationsmanual.

Grym applikation, jag är imponerad över att du hunnit implementera så mycket. Hoppas du får nytta av min feedback.

**Comment by SvanteArvedson** [comment]
Har uppdaterat min seeds, mina fixtures och min installationsmanual.

Tack för bra feedback :)
