### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by latana** [ba222ec/1DV450_ba222ec#13]
Hejsan!

Jag har tyvärr fått problem med att få igång projektet och börja testa.

Jag har följt dina instruktioner och migrerat upp databasen. Jag har även installerat gem 'tzinfo-data' då jag kör på windows.

När jag är inne i postman och testar får jag alltid felete "ActiveRecord::StatementInvalid in SessionsController#authenticate", Could not find table 'applications.

Och här påstår den att problemet finns "app/controllers/application_controller.rb:37:in `require_api_key'"

Är det någonting du har koll på? Jag testar vidare men hör gärna av dig om du vet vad som orsakar det.

**Comment by ba222ec** [comment]
Ojdå, det var olyckligt! Jag får se vad det kan bero på, var ingenting som hände när jag testade i nitrous. Hör av mig om/när jag hittar vad felet beror på. Hoppas att du kan testa fram till dess trots detta...

**Comment by SvanteArvedson** [comment]
Ojdå, det var olyckligt. Jag har glömt att ta med en sak i mina instruktioner...

Min _registreringsapplikation_ och mitt _webb-api_ delar på samma databas, men migreringsfilerna ligger seperat i de olika projektet (ex. tabellen _applications_ ligger definierad i registreringsappen). För att webb-api:et ska fungera så måste man köra rake **db:migrate** och rake **db:seed** också i registreringspplikationen. Registreringsapplikationen ligger i samma github-repo som webb-api:et i en annan katalog.

Jag ska uppdatera instruktionerna så att detta inte blir ett problem framåt och jag hoppas att du inte har fått för mycket extraarbete pga detta.

**Comment by latana** [comment]
Jag har tyvärr redan kört db:migrate. Jag har lyckats få liv i den men dessvärre har jag kommenterat bort koden "if api-key don't exist" i application_controller. Det bör väl gå att testa det mesta så länge jag inte testar utan api nyckel?
