### ISSUE TITLE
Labb 2 - Kommentar

### ISSUE THREAD

**Issue by latana** [ba222ec/1DV450_ba222ec#14]
Din kod är välstrukturerad och dina kommentarer är korta och omfattande. Ibland skulle jag vilja ha lite mer då metoderna drar iväg på längden. Annars riktigt trevligt att titta igenom.

**Comment by 1dv450** [comment]
Jag håller med. Känns välstrukturerat. Kanske jag valt och jobba lite mer med rescue_from än if-else-satser i felhanteringen för att enklare kunna samla olika typer av fel så som ActiveRecord::RecordNotFound och ge ett felmeddelande i jsonformat. Desa "fel" är nu ohanterade. 
Bra representation med länkar. Snyggt och prydligt med entities i Modeldelen. Någon speciell anledning till att du kör to_r på exp-datumet i din Json Web Token?
