### ISSUE TITLE
Testerna går inte att köra

### ISSUE THREAD

**Issue by Pajn** [ba222ec/1DV450_ba222ec#2]
Eftersom du har en NOT NULL constraint på users.name men inte med namn i din fixtures fil för användare så får man `ConstraintException` när man försöker köra testerna.

Eftersom tester är helt frivilligt här så är gör det ju dock inte så mycket.

**Comment by SvanteArvedson** [comment]
Lagat med commit 598bbcb9377706a55d1c5cd61a56bf8a49e2482a
