### ISSUE TITLE
Summering

### ISSUE THREAD

**Issue by Pajn** [ba222ec/1DV450_ba222ec#3]
Du har en väldigt prydlig och snygg rails-applikation som följer regelboken så långt jag som nybörjare i rails kan bedöma.
Jag gillar hur du använder ruby för att skriva snygg kod som exempelvis `unless admin_logged_in?`. En nit-picking är `not current_user.nil?` som du kan skriva som `current_user.present?` om du vill.

Du har inte så många kommentarer men med så ren kod som det är tycker jag personligen inte att de fattas utan koden är självförklarande.

Så kort sagt bra och trevlig kod, applikationen ser ut att fungera som den ska och är tydlig att använda. Jag hittar inte mycket att påpeka.

**Comment by SvanteArvedson** [comment]
Trevligt, tackar! :)
Fixade till de issues som du postat, ang. instruktionerna och testerna.
