### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by SheriefBadran** [ba222ec/1DV450_ba222ec#5]
Fungerar bra.

Ett tips är att kolla så att lösenordet inte får vara hur kort som helst. Jag kunde både registrera mig och logga in med ett tecken i lösenordet.

**Comment by SvanteArvedson** [comment]
Fixat med commit d8e53489e45eb7b0c884f0c8b36172b1638f8a7f
Minst 6 tecken i lösenordet.
