### ISSUE TITLE
Registrering

### ISSUE THREAD

**Issue by SheriefBadran** [ba222ec/1DV450_ba222ec#6]
Registreringen har samma problematik som login. Applikationen krashar för följande användarfall:

TC:
Gå till registeringsformuläret.
 Fyll i formuläret. Epost kan vara bugcheck@bugcheck.se. klicka på registrera. 
 Logga ut.
 Gå till registreringsformuläret.
 fyll i formuläret med samma uppgifter som förra gången förutom epost som skall vara bugcheck1@bugchek.se
 Klicka på registrera.

Användarfallet resulterar i följande felmeddelande:
SQLite3::ConstraintException: column name is not unique: INSERT INTO "users" ("created_at", "email", "name", "password_digest", "updated_at") VALUES (?, ?, ?, ?, ?)

Jag googlade som hastigast för att se om jag kunde åtgärda problemet men fick inte till det. Dock finns det fler som råkat ut för detta. Kanske är det kopplat till det problem pajn beskriver när tester körs??

**Comment by SvanteArvedson** [comment]
Detta är för att username också ska vara unikt för användaren, det som borde till är nog bättre felmeddelanden. Alternativt får jag tänka om, kanske det är bäst utan användarnamn...

 Får fundera på det, någonting borde göras iallafall...
