### ISSUE TITLE
Hantering av applikationer och api-nycklar för en användare.

### ISSUE THREAD

**Issue by SheriefBadran** [ba222ec/1DV450_ba222ec#7]
Gränssnittet är riktigt snyggt och bra. Mycket imponerad av att man kan registrera och hantera både applikation, applikationstyp och nyckel samt att varje användare kan ha flera applikationer. Negativt att anvädaren bekräftar borttagandet av en applikation via en promt, vilket kanske är bättre än (som i mitt fall) ingen bekräftelsefråga alls.

**Comment by SvanteArvedson** [comment]
Jo, promt var det som gck snabbast men är nog inte det bästa. Får fundera på hur man kan göra en annan lösning, kanske en div-modal...
